config/routes.rb
Rubypros::Application.routes.draw do

  root :to => 'jobs#index'

  metropoli_for :cities, :states, :countries, :cities_and_countries

  devise_for :companies, 
    :path_names => {
    :sign_in  => 'entrar',
    :sign_up  => 'registro',
    :sign_out => 'salir' 
  }

  resources :companies 
  resources :jobs do
    member do
      post "contact_company"
      get "expire"
      get "publish"
    end
  end

  resources :required_skills

  match '/terminos' => 'welcome#terminos'
  match '/privacidad' => 'welcome#privacidad'
  match '/ofertas' => 'jobs#index'
  match '/empresas' => 'companies#index'
  match '/registro' => 'devise#new'
  match '/nueva_oferta' => 'jobs#new'
  match '/busqueda' => 'jobs#search', :as => 'job_search'

  match '/acerca_de'=>'welcome#about'
  match '/codigo'=>'welcome#codigo'
  match '/licencia'=>'welcome#licencia'
  match '/:country'=>'redirecter#check_valid_country', as: 'country_jobs'

end

app/models/job.rb
# encoding: UTF-8
require "twitter"

class Job < ActiveRecord::Base
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::DateHelper

  belongs_to :company
  has_and_belongs_to_many :required_skills

  accepts_nested_attributes_for :required_skills

  validates_presence_of :company_id, :title, :description, :country
  validates_presence_of :at_least_one_type
  validate :extra_skill, :length => {:maximum => 140}

  FILTERS = %w{full_time part_time flexible remote}

  after_create :update_social_networks
  before_create :set_expiration_date, :set_publish_date

  metropoli_for :city
  metropoli_for :country

  scope   :ordered, order('id DESC')
  scope   :title_sorted, order("jobs.title ASC")
  scope   :date_sorted, order("jobs.publish_date DESC")
  scope   :not_expired, lambda { where("expiration_date > ?", Time.now) }
  scope   :expired, lambda { where("expiration_date <= ?", Time.now) }
  scope   :expire_today, lambda { where(expiration_date: Date.today..Date.tomorrow) }

  def self.filter_it(filters={})
    results = Job.includes(:company)
    unless filters.blank?
      results = results.where(FILTERS.collect do |filter|
        %|jobs.#{filter} = 't'| if eval(filters[filter.to_sym]) 
      end.compact.join(' OR '))
    end
    results
  end

  def self.from_country(id)
    where(:country_id => id)
  end

  def self.from_city(id)
    where(:city_id => id)
  end

  def self.with_keywords(keywords)
    search_fields = %w{jobs.title companies.title required_skills.skill_name}
    includes(:company, :required_skills).where(Helpers::LikeStatement.new(search_fields, keywords).to_array)
  end

  def self.next_jobs_batch(batch_size, last_date=DateTime.now + 1.second) # "1.second" is added for jobs that have just been created
    date_sorted.limit(batch_size).where("jobs.publish_date < ?", last_date)
  end

  def update_social_networks
    if Rails.env == 'production' or Rails.env == 'staging'
      Services::SocialNetworks::Updater.new(self.company.title, self.id, self.title).post_all
    end
  end

  def set_expiration_date
    self.expiration_date = 60.days.from_now.beginning_of_day
  end

  def set_publish_date
    self.publish_date = DateTime.now
  end

  def expire!
    self.expiration_date = DateTime.now.beginning_of_day
    self.save
  end

  def publish!
    set_expiration_date
    self.publish_date = DateTime.now
    self.save
  end

  def to_param
    "#{self.id}-#{self.title.parameterize}"
  end

  def at_least_one_type
    full_time || part_time || remote || flexible
  end

  def format_extra_skills
    extra_skill.split(',')
  end

  def formated_description
    self.description.gsub(/^h2\./,'h3.').gsub(/^h1\./,'h2.')
  end

  def latest_required_skills
    required_skills.all(:limit => 4, :order => "id desc" )
  end
  
  def to_s
    title
  end

  def origin
    city_name || country_name || city2
  end
  
  def has_logo
    logo.file?
  end

  def logo_url
    logo.url(:thumb)
  end

  def formatted_publish_date
    time_ago_in_words(publish_date)
  end
  
  def as_json(args={})
    args ||= {}
    super(args.merge!(:methods =>[:formatted_publish_date, :to_param, :origin, :logo_url, :has_logo] ,:include => {:company => {:only => [:title]}}))
  end
  
  private

  def logo
    company.logo
  end

end

app/controllers/jobs_controller.rb
# encoding: UTF-8
class JobsController < ApplicationController

  before_filter :new_company?, :only=>[:new]
  load_and_authorize_resource :through => :current_company, :except=>[:index, :search, :show, :my_jobs, :contact_company]
  layout :get_layout

  RANDOM = {'development' => 'RAND()', 'production' => 'random()'}[ENV['RACK_ENV']]

  def new
  end

  def create
    if @job.save
      redirect_to @job, :notice => I18n.t("notice.job.successfully_created")
    else
      render :action => "new"
    end
  end

  def index
    @jobs = Fetchers::JobFetcher.search(params)
    respond_to do |format|
      format.html {render :action => "index"}  
      format.json {render :json => @jobs }
    end
  end

  def search
    @jobs = Fetchers::JobFetcher.search(params)
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
  end

  def update
    params[:job][:required_skill_ids] = [] if params[:job][:required_skill_ids].nil?
    if @job.update_attributes(params[:job])
      redirect_to @job, :notice => I18n.t("notice.job.successfully_updated")
    else
      render :action => "new"
    end
  end

  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to(jobs_url, :notice=>"La oferta fue eliminada correctamente") }
      format.xml  { head :ok }
    end
  end

  def contact_company
    @job = Job.find(params[:id])
    cookies[:name] = { :value => params[:name], :expires => Time.now + 1.year }
    cookies[:email] = { :value => params[:email], :expires => Time.now + 1.year }
    ContactMailer.contact(@job, params[:name], params[:email], params[:message], params[:file]).deliver
    redirect_to(@job, :notice => "Tu mensaje fue enviado a #{@job.company.title} correctamente.")
  end

  def expire
    @job = Job.find(params[:id])
    if (@job.expire!)
      redirect_to get_redirect_to_path, :notice=> I18n.t("notice.job.successfully_expired")
    else
      redirect_to :back, :notice=> I18n.t("notice.job.not_expired")
    end
  end

  def publish
    @job = Job.find(params[:id])
    if (@job.publish!)
      redirect_to get_redirect_to_path, :notice=> I18n.t("notice.job.successfully_created")
    else
      redirect_to :back, :notice=> I18n.t("notice.job.not_published")
    end
  end

  private

  def get_layout
    (['index', 'search'].include? action_name) ? 'double_div' : 'application'
  end

  def new_company?
    if params[:new_company]
      redirect_to new_company_registration_path(:new_company => true)
    end
  end

  def get_redirect_to_path
    if request.referer.blank? || request.referer.include?('companies')
      company_path(@job.company.id)
    else
      job_path(@job)
    end
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
  def meta_title_for job
    "#{job.title} en #{job.company.title}"
  end

  def meta_description_for job
    result = "#{job.company.title} esta en busca de un #{job.title} en #{job.origin}. "
    if job.required_skills.any?
      result += "Algunas habilidades requeridas son #{job.required_skills.map(&:skill_name).to_sentence}. "
    end
    result += "Conoce mas acerca de esta oferta de trabajo en Ofertas Hacker"
    result
  end

  def meta_image_for job
    "https://image.ibb.co/moNZrF/oh_logo.png"
  end

  def installed_countries_names_with_cities
    CountryModelDecorator.names_of_countries_with_cities
  end

  def installed_countries_abbreviations
    CountryModelDecorator.abbr_of_countries_with_cities.map(&:downcase)
  end

  def country_image(abbr)
    "<img alt='#{abbr}_flag'  src='/#{abbr}.png'/>".html_safe
  end

  def get_job_type(job, text_only=false)
    
    content = "".html_safe
    job_options = []
    
    job.full_time ? job_options << "Tiempo completo" : ""
    job.part_time ? job_options << "Medio Tiempo" : ""
    job.remote ? job_options << "Remoto" : ""
    job.flexible ? job_options << "Flexible" : ""
    
    if text_only
      content +=job_options.join(", ")
    else
      content += content_tag(:p, job_options.join(", "))
    end
  end
  
  def display_segmented_list(job_list,even_or_odd='even')
    if block_given?
      job_list.each_with_index do |job, index|
        if index.send "#{even_or_odd}?"
           yield(job)
        end
      end
    end
  end
  
  def job_info(job)
    str=""
    job.city ? str+=" En #{job.city} " : ""
    str+=get_job_type(job,true)
    str
  end

  def condensed_information(job)
    str=""
    job.company ? str+=job.company.title : ""
    job.origin ? str+=" en #{job.origin} " : ""
    str+=get_job_type(job,true)
    str
    
  end
  
  def expired?(job)
    job.expiration_date < DateTime.now
  end

  def location_info_for(job)
    {:city_name => job.city_name.to_s, :country_name => job.country_name.to_s }.to_json.html_safe
  end
end

app/views/jobs/_contact_company.html.erb
<h3>¿Qué le quieres decir a la empresa?</h3>

<%= form_tag contact_company_job_path(job), :multipart => true  do %> 
  <%= label_tag t('.name') %>
  <%= text_field_tag :name, nil, :class => "required", :value => cookies[:name] %>        
  <%= label_tag t('.email') %>	 
  <%= text_field_tag :email, nil, :class => "required email", :value => cookies[:email] %>
  <%= label_tag t('.message') %>
  <li class="textarea"><%= text_area_tag :message, nil, :class => "required" %></li>
  <div id="cv">
  <span class="act_as_label">
    CV 
    <%= file_field_tag :file, :style=>"padding-left:10px;"%>
  </span>
  <%=image_tag "ajax-loader-contact.gif", :id=>"loader_contact", :style=>"position:absolute;bottom:26px;right:180px;"%>
  </div>
  <%= submit_tag "Enviar mensaje", :class=>"button right prepend-top", :id=>"contact_submit"%>
<% end %>

app/views/jobs/_form.html.erb
  <div class="infoCompany span-4 last">
    <p>Datos de la oferta</p>
  </div>
  <div class="generalForm span-12 last">
    <div class="firstColumn span-9 prepend-1">
    <%= form_for @job do |f| %> 
      <% if @job.errors.any? %>
        <div id="error_explanation">
          <h2>Revisa de nuevo porfa los siguientes detalles en la forma:</h2>
          <ul>
          <% @job.errors.full_messages.each do |msg| %>
            <li>- <%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>   

		    <p><%= f.label t('.title') + " *" %>
        <%= f.text_field :title %></p>

        <div id='location_info' data-countries_with_cities="<%= installed_countries_names_with_cities %>">
          <script type='text/javascript'>
            jQuery(function(){
              new LocationInputsApp(<%= location_info_for(f.object) %>).render();
            });
          </script>
        </div>
      </div>

	    <div class="skills span-20 prepend-1">
		    <%= f.label t('.job_type') + " *", :class => :non_block %><span class="desc">selecciona por lo menos un tipo</span>
        <ul class="form_checkboxes">
		      <li><%= f.check_box :full_time %> <%= f.label :full_time %> </li>
          <li><%= f.check_box :remote %> <%= f.label :remote %></li>
		      <li><%= f.check_box :part_time %> <%= f.label :part_time %></li>
		      <li><%= f.check_box :flexible %> <%= f.label :flexible %></li>
		    </ul>
	    </div>
   </div>
	  <div class="divShadow span-24">
      <div class="infoCompany span-4 last">
	      <p><%= t('.required_profile') %></p>
      </div>
      <div class="part2 span-20 last">
        <div class="skills span-20 prepend-1">
          <div class="clear"></div>
          <%= f.label "Habilidades requeridas" %>
            <ul class="form_checkboxes">
              <% for skill in RequiredSkill.all %>
                <li><%= check_box_tag 'job[required_skill_ids][]', skill.id, @job.required_skill_ids.include?(skill.id) %> <%= label_tag truncate(skill.skill_name, :length => 15) %> </li>
              <% end %>
	          </ul>
        </div>
        <div class="clear"></div>
   			<div id="extra_skill">
          <%= f.label t('.extra_skill'), :class => :non_block %> <span class="desc">separadas por comas</span>
          <%=f.text_field :extra_skill, :maxlength => "140", :cols=>6%></p>
        </div>
      </div>
		</div>
    <div class="divShadow span-24">
	    <div class="infoCompany span-4 last">
		    <p>Descripción de la Oferta</p>
	    </div>
		  <div class="descriptionForm span-20 last">
			  <div class="span-16 prepend-1">
          <%= f.label "Oferta *", :class => :non_block %>
         	<a href="#" id='centered_lightbox' rel="#trigger">Guía para formatear la descripción</a>
          <div class="overlay" id="trigger">  
	            <h2 style="margin:0px">Guia para formato de la descripción</h2> 
	            <div id="formatting_guide">
	              <p>
	                <%= render '/layouts/textileguide' %>
	              </p> 
	           </div>
          </div>
          <%= f.text_area :description, :rows=>"300"%>
			  </div>		
		  </div>     
	  </div> 
	  <div class="divShadow span-24 buttons">
			<div class="span-20 prepend-5 last">
				  <div class="calltoAction">
				      <% if @job.new_record? %>
		          	 <p><%= f.submit "Publicar oferta" %></p>
		          <% else %>
    		         <p><%= f.submit "Actualizar oferta" %></p>
    		      <% end %>
				  </div>
			</div>
		</div>
  <% end %>

app/views/jobs/_job.html.erb
<li class="job shadow" id = "<%= job.id%>">
  <%= hidden_field_tag "publish_date", job.publish_date%>
  <%= link_to(job) do %>
    <div class="span-4" >
      <%if job.has_logo %>
        <%=image_tag job.logo_url, :style=> "display:block;"%>
      <%else%>
        <h4><%= truncate(job.company.title, :length => 25)%></h4>
      <%end%>
    </div>
    <div class="prepend-3 span-5 last">
      <span class="small-tag">
        <%= "Hace #{time_ago_in_words(job.publish_date)}"%>
      </span>
    </div>
  <h1><%= truncate(job.title, :length => 40) %></h1>
  <p><%= truncate(condensed_information(job),:length => 70) %> </p>
  <% end %>
</li>

app/views/jobs/_jobs.html.erb
<div class='endless_content'>
  <div id="job_wrapper" class="discounted-item mainContent clear span-12">
    <ul class="posts even">
      <% display_segmented_list jobs, 'even' do |job| %>
        <%=render :partial =>'jobs/job', :locals=>{:job => job}%>
      <% end %>
    </ul>
  </div>
  <div id="job_wrapper" class="discounted-item mainContent last span-12">
    <ul class="posts odd">
      <% display_segmented_list jobs, 'odd' do |job| %>
        <%=render :partial =>'jobs/job', :locals=>{:job => job}%>
      <% end %>
    </ul>
  </div>
</div>

app/views/jobs/edit.html.erb
<%= render 'form' %>

app/views/jobs/index.html.erb
<%= content_for :search_form do %>
  <%= render 'layouts/search' %>
<% end %>

<%= content_for :search_filters do %>
  <%= render 'layouts/filter' %>
<% end %>

<script> $("li#ofertas a span").addClass("current")</script>

<div class="clearfix">
  <div id="skill_main">
    <% if current_company && @jobs.empty? %>
      <div class="mainContent span-23">
        <h1>Aun no tienes ofertas publicadas</h1>
        <%=link_to "Publica tu primera oferta", new_job_path, :class => "button"%>
      </div>
    <% else %>
      <%=hidden_field_tag :endless_path, "all_jobs"%>
      <%= render 'jobs/jobs', :jobs => @jobs %>
    <% end %>

  </div>
  <p id="back-top">
    <a href="#top"><span></span></a>
  </p>

</div>

app/views/jobs/new.html.erb
  <% custom_title "Nueva Oferta"%>
  <script> $("li#publicar a span").addClass("current")</script>
  <%= render 'form' %>

app/views/jobs/search.html.erb
<%= content_for :search_form do %>
  <%= render 'layouts/search' %>
<% end %>

<%= content_for :search_filters do %>
  <%= render 'layouts/filter' %>
<% end %>

<script> $("li#ofertas a span").addClass("current")</script>

<div class="clearfix">
  <div id="skill_main">
    <% if @jobs.empty? %>
      <div class="mainContent span-23 no_job_message">
        <h1>No hay ofertas con ese criterio de búsqueda</h1>
      </div>
    <% else %>
      <%=hidden_field_tag :endless_path, "all_jobs"%>
      <%= render 'jobs/jobs', :jobs => @jobs %>
    <% end %>
  </div>

  <p id="back-top">
    <a href="#top"><span></span></a>
  </p>
</div>

app/views/jobs/show.html.erb
<% content_for :head do %>
  <meta name="description" content="<%= @job.company.title %> está buscando un <%= @job.title %> en Ofertas Hacker. Lee más acerca del puesto en Ofertas Hacker.">

  <meta property="og:title" content="<%= meta_title_for(@job)  %>">
  <meta property="og:description" content="<%= meta_description_for(@job) %>">
  <meta property="og:image" content="<%= meta_image_for(@job) %>">

  <meta name="twitter:card" content="summary">
  <meta name="twitter:site" content="@ofertashacker">
  <meta name="twitter:domain" content="Ofertas Hacker">
  <meta name="twitter:title" content="<%= meta_title_for(@job) %>">
  <meta name="twitter:description" content="<%= meta_description_for(@job) %>">
  <meta name="twitter:image" content="<%= meta_image_for(@job) %>">
<% end %>

<div class="content">
  <div class="generalForm">
    <div class="nav-buttons">
      <% if can? :manage, @job%>
        <%=link_to "Editar", edit_job_path(@job), :class => "button"%>
        <% if expired?(@job)%>
          <%= link_to 'Publicar', publish_job_path(@job.id), :confirm => t('.publish_confirmation'), :class => "button" %>
        <% else %>
          <%= link_to 'Expirar', expire_job_path(@job.id), :confirm => t('.expire_confirmation'), :class => "button" %>
        <% end %>
        <%= link_to 'Borrar', @job, :confirm => t('.destroy_confirmation'), :method => :delete, :class => "button" %>
      <% end%>
    </div>
    <div id="left"><!--left-->
      <div id="logo">
        <%if @job.company.logo.file?%>
          <%= link_to (image_tag @job.company.logo.url(:medium)), company_path(@job.company), :id=>"company_logo" %>
        <%else%>

          <% if !@job.company.blank_profile?%>
            <%= link_to @job.company, :style=>"padding-bottom:10px;" do%>
              <h3><%= @job.company.title%></h3>
            <%end%>
          <%else%>
            <h3><%= @job.company.title%></h3>
          <%end%>
        <%end%>
      </div>
      <div class="clear"></div>
      <div id="info">
        <% unless @job.company.city.blank?%>
          <h2><%= @job.company.city %></h2>
        <% end %>
        <%=render :partial =>'companies/contact_info', :locals => {:company => @job.company}%>
      </div>
      <%= image_tag "shadow.gif" %>
      <br />

        <%= link_to "Contactar", "#", :id => "contact_button", :class => "button contact overlay_fade", :rel => "#contact_trigger" %>

        <div id="share_buttons">
          <div>
            <a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="OfertasHacker" data-lang="es">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
          </div>
          <div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#appId=170081829719593&amp;xfbml=1"></script><fb:like href="" send="false" layout="button_count" width="0" show_faces="true" action="recommend" font=""></fb:like>
          <div>
            <script type="text/javascript" src="http://platform.linkedin.com/in.js"></script><script type="in/share" data-counter="right"></script>
          </div>
        </div>
      </div>
      <div id="right">
        <div style="width:100%;overflow:hidden;"><h1><%= @job.title%></h1></div>
        <h4>En <%= @job.origin %>
          <%= @job.full_time ? ", Tiempo Completo".html_safe : nil%>
          <%= @job.part_time ? ", Medio Tiempo".html_safe : nil%>
          <%= @job.remote ? ", Remoto".html_safe : nil%>
          <%= @job.flexible ? ", Horario Flexible".html_safe : nil%>
        </h4>
        <% for skill in @job.required_skills %>
          <div class="tag">
            <span><%= skill.skill_name %></span>
          </div>
        <% end %>
        <%unless @job.extra_skill.blank?%>
          <% for skill in @job.format_extra_skills%>
            <div class="tag">
              <span><%= truncate(skill, :length => 110) %></span>
            </div>
          <% end %>
        <%end%>

        <div class="clear"></div>
        <div class="small-label"><%=t '.publish_date' %> <%=l @job.publish_date.to_date %></div>
        <p>

        <div id="job_description">
          <p><%= RedCloth.new(@job.formated_description,[
              :filter_html,
              :filter_styles,
              :filter_classes,
              :filter_ids
            ]).to_html.html_safe %></p>
        </div>

      </div><!--/right-->

      <div class="clear"></div>
    </div>

  </div>
       
<% content_for :bottom do %>
	<div class="overlay contact" id="contact_trigger">
	  <%= render :partial => 'contact_company', :locals=>{:job=>@job}%>
	</div>
<% end %>