config/routes.rb
Rubypros::Application.routes.draw do

  root :to => 'jobs#index'

  metropoli_for :cities, :states, :countries, :cities_and_countries

  devise_for :companies, 
    :path_names => {
    :sign_in  => 'entrar',
    :sign_up  => 'registro',
    :sign_out => 'salir' 
  }

  resources :companies 
  resources :jobs do
    member do
      post "contact_company"
      get "expire"
      get "publish"
    end
  end

  resources :required_skills

  match '/terminos' => 'welcome#terminos'
  match '/privacidad' => 'welcome#privacidad'
  match '/ofertas' => 'jobs#index'
  match '/empresas' => 'companies#index'
  match '/registro' => 'devise#new'
  match '/nueva_oferta' => 'jobs#new'
  match '/busqueda' => 'jobs#search', :as => 'job_search'

  match '/acerca_de'=>'welcome#about'
  match '/codigo'=>'welcome#codigo'
  match '/licencia'=>'welcome#licencia'
  match '/:country'=>'redirecter#check_valid_country', as: 'country_jobs'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about
  end

  def terminos
  end

  def privacidad
  end

  def codigo
  end

  def licencia
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_privacidad.html.erb
<%= link_to "INNKU Solutions SA de CV", "http://www.innku.com", :target=>:_blank %> de conformidad con lo dispuesto en la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, vigente en la República Mexicana hace de tu conocimiento lo siguiente:
<ol>
  <li>Que únicamente recopilamos tus datos personales no sensibles para los siguientes propósitos: I.) Para fines de identificación. II) Para fines estadísticos y III) Para eventualmente contactarlo vía correo electrónico o teléfono con el fin de compartirle noticias de interés en la rama de ofertas u oportunidades de empleo para desarrolladores.</li>

  <li>Que tus datos personales jamás serán divulgados ni compartidos con terceros, ni se les dará un uso distinto al señalado en el primer punto.</li>

  <li>Que <%= link_to "INNKU Solutions SA de CV", "http://www.innku.com", :target=>:_blank %> tratará y resguardará a tus datos personales con base en los principios de licitud, calidad, consentimiento, información, finalidad, lealtad, proporcionalidad y responsabilidad consagrados en la Ley Federal de Protección de Datos Personales en Posesión de los Particulares.</li>

  <li>Que la persona responsable del manejo de tus datos personales será eñ señor Alberto Padilla Luengas, quien forma parte de la administración de <%= link_to "INNKU Solutions SA de CV", "http://www.innku.com", :target=>:_blank %> misma que tiene como domicilio el ubicado en Paseo de la Esperanza 913 Altos A, Col. Valle del Mirador en San Pedro Garza García, Nuevo León. C.P. 66260.</li>

  <li>Que respecto de tus datos personales, tú podrás ejercer los derechos de acceso, rectificación, cancelación y/u oposición (Derechos ARCO) mediante el envío de un correo electrónico a la siguiente dirección: ofertashacker@innku.com. Para ser procesada tu petición, ésta deberá incluir todos y cada uno de los requisitos previstos en el artículo 29 de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares.</li>

  <li>Que <%= link_to "INNKU Solutions SA de CV", "http://www.innku.com", :target=>:_blank %> se reserva el derecho a modificar el presente Aviso de Privacidad en el futuro. En todo caso, cualquier modificación al mismo se hará de tu conocimiento mediante el envío de un correo electrónico a la cuenta que tu nos proporciones inicialmente para hacer de tu conocimiento el presente Aviso de Privacidad y/o mediante la publicación del mismo en la página web www.ofertashacker.com/privacidad.</li>

  <li><%= link_to "INNKU Solutions SA de CV", "http://www.innku.com", :target=>:_blank %> no será responsable en el caso de que el usuario no reciba la referida notificación de cambio en el Aviso de Privacidad si existiere algún problema con su cuenta de correo electrónico o de transmisión de datos por internet. Sin embargo, por tu seguridad, el Aviso de Privacidad vigente estará disponible en todo momento en la página web señalada en el punto anterior.</li>

  <li>Que este Aviso de Privacidad cumple con los requisitos establecidos en la Ley Federal de Protección de Datos Personales en Posesión de los Particulares vigente. </li>

  <li>Asimismo, <%= link_to "INNKU Solutions SA de CV", "http://www.innku.com", :target=>:_blank %> se compromete a no vender, intercambiar, transferir, compartir, publicar o difundir a terceros ajenos al <%= link_to "INNKU Solutions SA de CV", "http://www.innku.com", :target=>:_blank %>, los datos que nos proporciones al crear tu perfil, publicar direcciones, o cualquier otra información que ingreses en nuestro sistema. Tus datos son tuyos. La única forma en que nos veríamos obligados a revelar tus datos es mediante la orden de una autoridad competente.</li>

  <li>Si eventualmente <%= link_to "INNKU Solutions SA de CV", "http://www.innku.com", :target=>:_blank %> se llegara a fusionar o asociar con alguna nueva empresa, sólo compartiremos tus datos si contamos con tu autorización expresa. Nosotros te contactaremos en dicho caso y te proporcionaremos un mecanismo ágil y sencillo para recabar tu autorización o removerte de nuestra base de datos.</li>

  <li>En todo momento, mediante el acceso a tu cuenta, podrás modificar o rectificar los datos que nos has proporcionado. De la misma forma, podrás cancelar tu cuenta y en consecuencia darte de baja de nuestras bases de datos.</li>

  <li>Como usuario, tú eres responsable de la veracidad de la información que ingreses al sistema.</li>

  <li>Si lo autorizas y la configuración de tu máquina nos lo permite, enviaremos un archivo llamado “cookie” que se instalará en tu disco duro para permitirnos identificar las preferencias que hayas seleccionado, en su caso, para mejorar tu experiencia en nuestro sitio. Ninguna de la información que se almacene en el “cookie” será divulgada por <%= link_to "INNKU Solutions SA de CV", "http://www.innku.com", :target=>:_blank %>. Entre otros datos que puede almacenar la “cookie” se encuentran tu nombre, preferencias, teléfono, etc. Ninguno de ellos será divulgado de conformidad con la presente política de privacidad.</li>

  <li>Por cuestiones de seguridad, al aceptar la presente política de privacidad te será enviado un correo de verificación y validación que deberás de confirmar para concluir tu aceptación y registro.</li>

  <li>Cuando haya sido solicitado por <%= link_to "INNKU Solutions SA de CV", "http://www.innku.com", :target=>:_blank %> se cifrará toda la información que se envía a través de los formularios que se encuentran en las áreas seguras de su sitio. Podrás identificar las áreas seguras porque las mismas tendrán el prefijo https:// en donde la “s” indica que se trata de un área segura.</li>

  <li>No obstante que <%= link_to "INNKU Solutions SA de CV", "http://www.innku.com", :target=>:_blank %> utiliza la tecnología más avanzada para salvaguardar los datos que nos envías, existe la probabilidad de que pueda haber un defecto en la programación de las aplicaciones que utilizamos, que permita el acceso forzado a la información. Aún y cuando esta situación se llegara a dar, tus datos están protegidos mediante procesos de cifrado avanzado que hacen imposible la recuperación útil de la información por un tercero ajeno a <%= link_to "INNKU Solutions SA de CV", "http://www.innku.com", :target=>:_blank %>.</li>
</ol>
</p>

app/views/welcome/about.html.erb
<div class="content about_wrapper">
  <% custom_title "Acerca de"%>
  <div id="about">
    <div id="welcome">
      <div id="top"><%= image_tag 'ribbon1.png'%><h1>Las mejores ofertas para los mejores desarrolladores</h1><%= image_tag 'ribbon2.png'%></div>
      <div id="sub_titles">
      <h3>¿Qué es Ofertas Hacker?</h3>
      <p id="welcome_info">
      Es un espacio para publicar y encontrar oportunidades de <br />
      trabajo para desarrolladores latinoamericanos.<br />
      </p>
      <div class="link" id="link1">
        <%= link_to new_job_path(:new_company => "true") do %>
          <span class="big">Publica una oferta</span><br />
          <span>para empresas</span>
        <% end %>
      </div>

      <div class="link" id="link2">
        <%= link_to jobs_path do %>
          <span class="big">Busca una oferta</span><br />
          <span>para desarrolladores </span>
        <% end %>
      </div>
      </div>
    </div>
    <div id="middle">
      <h3>No, nadie se quiere hacer rico a partir de este sitio.</h3>
      <p>
        Es enserio, este sitio no tiene fines de lucro, por el momento es gratis
        para todos, y si llegamos a cobrar en algún 
 				punto será con el firme y único objetivo de mantener vivo este espacio.
      </p>
      <h3>¿Por qué?</h3>
      <p>
      El objetivo de Ofertas Hacker es promover el desarrollo de software en
      países latinoamericanos y encontrar las 
			mejores ofertas de trabajo para los mejores desarrolladores.
      </p>
    </div>
    <div id="bottom">
      <div id="title">
        <h3>¿Quieres aportar a este proyecto?</h3>
        <p id="sub">Nos encantaría que tu empresa forme parte del desarrollo de este producto para mejorarlo cada vez más y más rápido</p>
      </div>
      <h4>Necesitamos</h4>
      
      <div id="boxes">

        <div id="box1">
          <div class="box">
            <%=image_tag "difusion.png"%>
            <div class="info">
              <h4>Difusión</h4>
              <p>Invita a las empresas que busquen desarrolladores a publicar sus vacantes. </p>
            </div>
          </div>
        </div>

        <div id="box2">
          <div class="box">
            <%=image_tag "difusion.png"%>
            <div class="info">
              <h4>Mucha difusión</h4>
              <p>Dile a los desarrolladores que esten al pendiente de las ofertas.</p>
            </div>
          </div>
        </div>


        <div id="box3">
          <div class="box">
            <%=image_tag "difusion.png"%>
            <div class="info">
              <h4>Más difusión</h4>
              <p>Como se te ocurra pero ayúdanos a hacer de este un gran espacio. </p>
            </div>
          </div>
        </div>

        <div id="box4">
          <div class="box">
            <%=image_tag "mano.png"%>
            <div class="info">
              <h4>También manos, mentes e ideas</h4>
              <p>Estamos abiertos a recibir tu apoyo para crear juntos un mejor producto.</p>
            </div>
          </div>
        </div>

      </div>
    </div>
    <%=image_tag 'bottom-line.png', :id =>'bottom_line'%>
  </div>
</div>

app/views/welcome/codigo.html.erb
<div class="content open_wrapper">

  <div id="top">
    <div id="left_side">
      <h1>Este es un proyecto de Código Abierto</h1>
      <h2>¿Qué quiere decir?</h2>
      <p>
      Que quien sea puede colaborar, aportar, mejorar e intervenir en el proyecto. 
      Es de todos para todos.
      </p>

      <ul>
        <li>Está hecho con Ruby on Rails</li>
        <li>El código está en Github</li>
        <li>No es perfecto pero siempre estará en movimiento</li>
      </ul>
    </div>
    <%= image_tag 'open_source.png', :alt => "Open Source" %>
  </div>

  <div id="bottom">
    <div id="boxes">

      <div>
        <h2>¿Qué se ha hecho, qué estamos haciendo, qué sigue?</h2>
        <%=link_to "Ver Proyecto", "https://www.pivotaltracker.com/projects/153065", :class=> "button", :target =>:_blank %>
        <p>Puedes ver el avance del proyecto en nuestra cuenta de:
        <%= image_tag "pivotal.png", :alt => "Pivotal Tracker"%>
        </p>
      </div>

      <div id="middle">
        <h2>¿Quieres dar ideas, quejarte o felicitarnos?</h2>
        <%=link_to "Ir al Foro", "http://getsatisfaction.com/ofertashacker", :class=> "button", :target =>:_blank %>
        <p>Te invitamos a nuestro foro de discusión en:
        <%= image_tag "get_satisfaction.png", :alt => "Get Satisfaction"%>
        </p>
      </div>

      <div>
        <h2>¿Quieres aportar con código y ayudarnos a avanzar?</h2>
        <%=link_to "Ver Repositorio", "http://www.github.com/innku/ofertashacker", :class=> "button", :target =>:_blank %>
        <p>“Fork me” en
        <%= image_tag "github.png", :alt => "Github"%>
        </p>
      </div>

    </div>
    <div id="licencia">Este software libre está bajo la licencia GPL v3 <%= link_to "Ver términos", licencia_path %></div>
  </div>
</div>

app/views/welcome/contact.html.erb
<div class="content">
  <% custom_title "Contacto"%>
  <h1>Contacto</h1>
</div>

app/views/welcome/licencia.html.erb
<div class="content">


  <!-- Scrolling content container -->
  <div class="terms_of_use">
    <h1>Licencia GPL v3</h1>
    <%=render 'licencia'%>
  </div>



</div>

app/views/welcome/privacidad.html.erb
<div class="content">
  <!-- Scrolling content container -->
  <div class="terms_of_use" style="padding:20px;">
    <h1>Aviso de Privacidad</h1>
    <%= render 'privacidad'%>
  </div>
</div>

app/views/welcome/terminos.html.erb
<div class="content">
  <!-- Scrolling content container -->
  <div class="terms_of_use">
    <h1>Términos de Uso</h1>
    <%=render 'terminos'%>
  </div>
</div>