config/routes.rb
Rubypros::Application.routes.draw do

  root :to => 'jobs#index'

  metropoli_for :cities, :states, :countries, :cities_and_countries

  devise_for :companies, 
    :path_names => {
    :sign_in  => 'entrar',
    :sign_up  => 'registro',
    :sign_out => 'salir' 
  }

  resources :companies 
  resources :jobs do
    member do
      post "contact_company"
      get "expire"
      get "publish"
    end
  end

  resources :required_skills

  match '/terminos' => 'welcome#terminos'
  match '/privacidad' => 'welcome#privacidad'
  match '/ofertas' => 'jobs#index'
  match '/empresas' => 'companies#index'
  match '/registro' => 'devise#new'
  match '/nueva_oferta' => 'jobs#new'
  match '/busqueda' => 'jobs#search', :as => 'job_search'

  match '/acerca_de'=>'welcome#about'
  match '/codigo'=>'welcome#codigo'
  match '/licencia'=>'welcome#licencia'
  match '/:country'=>'redirecter#check_valid_country', as: 'country_jobs'

end

app/models/company.rb
class Company < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs, :dependent => :destroy
    
  validates :title, :presence => true, :uniqueness => true
  validates_format_of :website, :with => /^(http:\/\/(www\.)?|(www\.)?)\w+\.\D{2,}.*$/i, :on => :update, :if => :website?
  validates_format_of :contact_email, :with => /^\w(\w|[.-])+@\w+\.\w{2,}$/i, :on => :update, :if => :contact_email?
  validates_format_of :facebook, :with =>/^(\/?\w+|((http:\/\/(www\.)?|(www\.)?)facebook.com\/\w+))$/i, :on => :update, :if => :facebook?
  validates_format_of :twitter, :with => /^((\/|@)?\w+|((http:\/\/(www\.)?|(www\.)?)twitter.com\/\w+))$/i, :on => :update, :if => :twitter?

  validates_attachment_content_type :logo, 
                                    :content_type => ['image/jpg','image/jpeg', 
                                                      'image/png', 'image/gif']

  attr_accessible :email, :password, :password_confirmation,
                  :remember_me, :title, :city_name, :logo, :description,
                  :phone1, :phone2, :contact_email, :linkedin, :facebook, :twitter, :website, :role, :terms_of_service

  validates_acceptance_of :terms_of_service

	metropoli_for :city
  scope :members, where(:role => "member")
  
  DEFAULT_LOGO_ROUTE = "/images/shareIcon.png"

  has_attached_file :logo, :styles => {:list => "150x100", :medium => "200x100>", :thumb => "130x35>"},
                            :default_style => :thumb,
                            :storage => {
                              'development' => :filesystem,
                              'test' => :filesystem,
                              'staging' => :s3,
                              'production' => :s3
                            }[Rails.env],
                            :s3_credentials => "#{Rails.root}/config/s3.yml",
                            :url => "../files/#{ENV['RAILS_ENV']}/:attachment/:id/:style/:basename.:extension",
                            :path => "public/files/#{Rails.env}/:attachment/:id/:style/:basename.:extension",
                            :bucket => 'rubypros',
                            :default_url => DEFAULT_LOGO_ROUTE

  def has_logo
    self.logo.file?
  end

  def to_s
    title
  end

  def to_param
    "#{self.id}-#{self.title.parameterize}"
  end

  def admin?
    self.role == "admin"
  end
  
  def member?
    self.role == "member"
  end
  
  def logo_url
    if Rails.env == 'production'
      self.logo.url
    else
     self.logo.path.nil? ?  DEFAULT_LOGO_ROUTE : self.logo.path[6..-1]
    end
  end

  def facebook?
    !self.facebook.blank?
  end

  def website?
    !self.website.blank?
  end

  def twitter?
    !self.twitter.blank?
  end
  
  def contact_email?
    !self.contact_email.blank?
  end
  
  def phone1?
    !self.phone1.blank?
  end
  
  def latests_jobs
    jobs.all(:limit => 4, :order=> "id desc")
  end

  def formated_facebook
    start = 0
    if (self.facebook.match(/(^http:\/\/(www\.)?)facebook.com/i))
      start = self.facebook[7..-1].index('/') + self.facebook.index('/') + 3
    elsif (self.facebook.match(/^(www\.)?facebook.com/i) )
      start = self.facebook.index('/') + 1
    elsif (self.facebook.index('/')==0)
      start = 1
    end
    return "http://www.facebook.com/#{self.facebook[start..-1]}"
  end

  def facebook_text
    start = 0
    if (self.facebook.match(/(^http:\/\/(www\.)?)facebook.com/i))
      start = self.facebook[7..-1].index('/') + self.facebook.index('/') + 3
    elsif (self.facebook.match(/^(www\.)?facebook.com/i) )
      start = self.facebook.index('/') + 1
    elsif (self.facebook.index('/')==0)
      start = 1
    end
    return "facebook.com/#{self.facebook[start..-1]}"
  end

  def formated_twitter
    start = 0
    if (self.twitter.match(/(^http:\/\/(www\.)?)twitter.com/i))
      start = self.twitter[7..-1].index('/') + self.twitter.index('/') + 3
    elsif (self.twitter.match(/^(www\.)?twitter.com/i) )
      start = self.twitter.index('/') + 1
    elsif (self.twitter.index('/')==0)
      start = 1
    elsif (!self.twitter.index('@').nil?)
      start = 1
    end
    return "http://www.twitter.com/#{self.twitter[start..-1]}"
  end

  def twitter_text
    start = 0
    if (self.twitter.match(/(^http:\/\/(www\.)?)twitter.com/i))
      start = self.twitter[7..-1].index('/') + self.twitter.index('/') + 3
    elsif (self.twitter.match(/^(www\.)?twitter.com/i) )
      start = self.twitter.index('/') + 1
    elsif (self.twitter.index('/')==0)
      start = 1
    elsif (!self.twitter.index('@').nil?)
      start = 1
    end
    return "@#{self.twitter[start..-1]}"
  end

  def formated_website
    start = 0
    if (self.website.match(/^http:\/\/(www\.)?\w+\.\w+.*/i))
      return self.website
    elsif (self.website.match(/^(www\.)?\w+\.\w+.*/i))
      return "http://#{self.website}"
    else
      return self.website
    end
  end
  
  def formated_description
    self.description.gsub(/^h2./,'h3.').gsub(/^h1./,'h2.')
  end

  def blank_profile?
    #TODO Refactor this method
    self.city.blank? && !self.logo.file?  && self.twitter.blank? && self.facebook.blank? && self.contact_email.blank?  && self.website.blank? && self.description.blank?
  end

  def origin
    if city.present?
      city_name 
    else
      city2
    end
  end

end

app/controllers/companies_controller.rb
# encoding: UTF-8
class CompaniesController < ApplicationController
  before_filter :new_company?, :only=>[:create]
  load_and_authorize_resource
    
  def index
    @companies = Company.all(:order => "RANDOM()").select{|c| !c.blank_profile?}
  end
  
  def show
    if @company.blank_profile?
      redirect_to edit_company_path @company
      return
    else
      @available_jobs = @company.jobs.not_expired.title_sorted
      @expired_jobs = @company.jobs.expired.title_sorted
    end
  end
  
  def edit
  end
  
  def update
    if @company.update_attributes(params[:company])
      redirect_to company_path, :notice => I18n.t("notice.company.successfully_updated")
    else
      render :action => 'edit'
    end
  end
  
   def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to(companies_url, :notice=>"La empresa fue eliminada correctamente") }
      format.xml  { head :ok }
    end
  end
  
  private

  def initial_batch?
    params[:last_date].present?
  end

  def new_company?
    if params[:new_company]
      redirect_to new_company_registration_path(:new_company => true)
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper

end

app/views/companies/_contact_info.html.erb
<ul>
  <% if company.website? %>
    <li><%= link_to "#{truncate(company.website, :length => 30)}", (company.formated_website), :target => :_blank%></li>
  <% end %>
  <% if company.contact_email? %>
    <li> <%= mail_to company.contact_email, truncate(company.contact_email, :length => 30)%> </li>
  <% else %>
    <li> <%= mail_to company.email, truncate(company.email, :length => 30)%> </li>
  <% end %>
  <% if company.twitter? %>
    <li> <%= link_to "#{truncate(company.twitter_text, :length => 30)}", (company.formated_twitter), :target => :_blank%> </li>
  <% end %>
  <% if company.facebook? %>
    <li> <%= link_to "#{truncate(company.facebook_text, :length =>30)}", (company.formated_facebook), :target => :_blank%> </li>
  <%end%>
</ul>

app/views/companies/_form.html.erb
<div class="mainContent clear span-24">
  <% custom_title "Editar Perfil"%>
  <div class="infoCompany span-4">
    <p>Datos de la empresa</p>
  </div>
  <div class="generalForm span-12 prepend-1">
    <%= form_for @company, :html => { :multipart => true } do |f| %>
      <% if @company.errors.any? %>
        <div id="error_explanation">
          <h2>Revisa de nuevo porfa los siguientes detalles en la forma:</h2>
          <ul>
            <% @company.errors.full_messages.each do |msg| %>
              <li>- <%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>   

      <%= f.label t('.title') + " *" %>
      <%= f.text_field :title %>
      <%= f.label t('.city') %>
      <%= f.text_field :city_name, :class => 'city_autocomplete' %>
      <%= f.label t('.email') + " *" %>
      <%= f.text_field :email%>

      <%= f.label "Logo" %>
      <%= f.file_field :logo %>
      <hr class="span-12">
      <%=image_tag @company.logo.url %>
      <span class="clear"></span>

    </div><!--/generalform -->
    <div class="divShadow span-24">

      <div class="infoCompany span-4">
        <p>Descripción de la empresa</p>
      </div>
      <div class="descriptionForm span-16 prepend-1">
        <%= f.label t('.description'), :class => :non_block %>
        <a href="#" class='overlay_fade' rel="#trigger">Guía para formatear textareas</a>
        <div class="overlay" id="trigger">  
          <h2 style="margin:0px">Guia para formato de text areas</h2> 
          <div id="formatting_guide">
            <p>
            <%= render '/layouts/textileguide' %>
            </p> 
          </div>
        </div>
        <%= f.text_area :description %>
      </div>
    </div><!--/description -->

    <div class="divShadow span-24">
      <div class="infoCompany span-4">
        <p>Contacto</p>
      </div>
      <div id="contacto" class="span-16 prepend-1">
        <div class="span-9 ">
          <%= f.label "e-mail de contacto" %>
          <%= f.text_field :contact_email %>
          <span><%= f.label "website" %></span>
              <p>
              <%= f.text_field :website %></p>
              <div class="clear"></div>


              <span id="label_img"><%= f.label "facebook" %> <%=image_tag 'facebook_logo.png'%></span>
              <p>
              <%= f.text_field :facebook %></p>
              <div class="clear"></div>

              <span id="label_img"><%= f.label "twitter" %> <%=image_tag 'twitter-logo.png'%></span>
              <p>
              <%= f.text_field :twitter %></p>
              <div class="clear"></div>

            </div>

          </div>
        </div>
        <div class="divShadow span-24 buttons">
          <div class="span-20 prepend-5 last">
            <div class="calltoAction">
              <p><%= f.submit "Actualizar" %></p>
            </div>
          </div>
        </div> 
      <% end %>
    </div>

app/views/companies/_jobs_list.html.erb
<% jobs.each do |job| %>  
  <li class="<%=item_class%>">
    <%= link_to(job_path(job), :class => 'item')  do %>
        <div class="item_wrapper">
          <div class="title">
            <%= job.title %>
          </div>
          <div class="details">
            <%= get_job_type(job, true) %>
          </div>
        </div>
    <% end %>
    <% if current_company == company %>
      <% if expired?(job) %>
        <%= link_to 'Publicar', publish_job_path(job.id), :confirm => t('jobs.show.publish_confirmation'), :class => "button" %>
      <% else %>
        <%= link_to 'Expirar', expire_job_path(job.id), :confirm => t('jobs.show.expire_confirmation'), :class => "button" %>
      <% end %>
    <% end %>
  </li>
<% end %> 

app/views/companies/edit.html.erb
<% custom_title @company.title %>
<script> $("li#perfil a span").addClass("current")</script>
<%= render 'form' %>

app/views/companies/index.html.erb
<div class="content">
  <% custom_title "Empresas"%>
  <script> $("li#empresas a span").addClass("current")</script>
	<div class="companies_wrapper">
		<div class="companies_sidebar">
			<div class="sidebar_top">
				<p>¿Tu empresa necesita developers y no est&aacute; en la lista?</p>
				<p><span>¡Reg&iacute;strate ya!</span></p>
				<%= link_to "Registrarte ahora", new_company_registration_path(), :class => "button"  %>
			</div>
			<div class="sidebar_bottom">
				<p>Mant&eacute;nte informado</p>
				<ul>
          <li><%= link_to (image_tag "facebook.png", :alt => "FB Rubypros",:onmouseout=>"this.src='/assets/facebook.png'",:onmouseover=>"this.src='/assets/facebook1.png'"), "http://www.facebook.com/OfertasHacker", :target=>:_blank %></li>
				  <li><%= mail_to("ofertashacker@innku.com", image_tag("mail.png", :onmouseout=>"this.src='/assets/mail.png'", :onmouseover=>"this.src='/assets/mail1.png'")) %></li>
          <li><%= link_to (image_tag "twitter.png", :alt => "Twitter",:onmouseout=>"this.src='/assets/twitter.png'", :onmouseover=>"this.src='/assets/twitter1.png'"), "http://www.twitter.com/ofertashacker", :target =>:_blank %></li>
				</ul>
			</div>
		</div>
	  <% @companies.each do |company| %>
	    <div class="company_profile shadow">
	        <span>
	        	<h2><%= link_to truncate(company.title, :length =>  25), company_path(company) %></h2>
            <% unless company.origin.blank?%><p><%= "En #{company.origin}" %></p><%end%>
            <% if company.website? %>
              <%= link_to "#{truncate(company.website, :length => 50)}", (company.formated_website), :target => :_blank%>
            <% end %><br />
		        <% if company.twitter?%>
		          <%= link_to "#{truncate(company.twitter_text, :length => 50)}", (company.formated_twitter), :target => :blank%><br />
		        <%end%>
		        <% if company.facebook?%>
              <%= link_to "#{truncate(company.facebook_text, :length => 50)}", (company.formated_facebook), :target => :blank%> 
		          <br />
		        <%end%>
	        </span>
	        <%if company.logo?%>
	        <%=link_to (image_tag company.logo.url(:list)), company%>
	        <%end%>

	      <div class="clear"></div>
	   </div>   
		<% end %>
	</div>
	
</div>

app/views/companies/my_jobs.html.erb
<script> $("li#mis_ofertas a span").addClass("current")</script>
<%=hidden_field_tag :endless_path, "my_jobs", :company=> "#{current_company.id}"%>

<div class="clearfix">
  <% if current_company && @jobs.empty? %>
    <div class="mainContent span-23">
      <h1>Aun no tienes ofertas publicadas</h1>
      <%=link_to "Publica tu primera oferta", new_job_path, :class => "button"%>
    </div>
  <%else%>
    <%= render :partial => "jobs/jobs", :locals => {:jobs => @jobs} %>
  <%end%>

  <p id="back-top">
    <a href="#top"><span></span></a>
  </p>
</div>

app/views/companies/show.html.erb
<div class="content" >
  <% custom_title @company.title%>
  <script> $("li#perfil a span").addClass("current")</script>
  <div class = "nav-buttons">
    <ul id="prueba">
    <% if current_company && current_company.admin? %>
      <li><%= link_to t('.company_index'), companies_path(), :class => "button"  %></li>
    <% end %>
    <% if can? :update, @company %>
      <li><%= link_to t(:edit), edit_company_path(@company), :class => "button" %></li>
    <% end %>
    <% if can? :manage, @company %>
      <li><%= link_to "Eliminar empresa", company_path(@company), :class => "button", :confirm => "¿Estás seguro de eliminar #{@company.title}?", :method => :delete %></li>
    <% end %>
    </ul>
  </div>

  <div id="logoperfil">
    
  </div>
  <div class="generalForm">
    <div id="left">
      <%if @company.logo.file?%>
        <%= link_to (image_tag @company.logo.url(:medium)), company_path(@company), :id=>"company_logo" %>
      <%else%>
          <h3><%= @company.title%></h3>
      <%end%>
      <div class="clear"></div>
      <div id="info">
        <% if @company.origin.present?%>
          <h2><%= @company.origin %></h2>
        <% end %>
        <%= render :partial => 'contact_info', :locals => {:company => @company}%>
      </div>
      <%= image_tag "shadow.gif" %>
    </div>
    <div id="right">
      <h1><%= @company.title %></h1>
      <div id="job_description">
        <p><%= @company.description ? RedCloth.new(@company.formated_description).to_html.html_safe : "" %></p>
      </div>
      <div class="clear"></div>
      <% if @company.jobs.present? %>
        <br />

        <% if @available_jobs.any? %>
          <h3>Estamos Buscando:</h3>
          <ul id="jobs_list" class="admin-list">
            <%= render "jobs_list", :jobs => @available_jobs, :item_class => "not-expired", :company => @company %>
          </ul>
        <% end %>

        <% if @expired_jobs.any? %>
          <% if current_company == @company %>
            <h3>Ofertas expiradas:</h3>
            <ul id="expired_jobs_list" class="admin-list">
              <%= render "jobs_list", :jobs => @expired_jobs, :item_class => "expired", :company => @company %>
            </ul>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="clear"></div>
  </div>
</div>