config/routes.rb
Rubypros::Application.routes.draw do

  root :to => 'jobs#index'

  metropoli_for :cities, :states, :countries, :cities_and_countries

  devise_for :companies, 
    :path_names => {
    :sign_in  => 'entrar',
    :sign_up  => 'registro',
    :sign_out => 'salir' 
  }

  resources :companies 
  resources :jobs do
    member do
      post "contact_company"
      get "expire"
      get "publish"
    end
  end

  resources :required_skills

  match '/terminos' => 'welcome#terminos'
  match '/privacidad' => 'welcome#privacidad'
  match '/ofertas' => 'jobs#index'
  match '/empresas' => 'companies#index'
  match '/registro' => 'devise#new'
  match '/nueva_oferta' => 'jobs#new'
  match '/busqueda' => 'jobs#search', :as => 'job_search'

  match '/acerca_de'=>'welcome#about'
  match '/codigo'=>'welcome#codigo'
  match '/licencia'=>'welcome#licencia'
  match '/:country'=>'redirecter#check_valid_country', as: 'country_jobs'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_filter.html.erb
<div class='filters full'>
  <div class='container'>
  <%= label_tag  '', 'Filtra tu búsqueda por: ', :class => 'description' %>
  <ul id="mainMenu">
    <li><input type="checkbox" id="full_time" checked="true"><label for="full_time">Tiempo completo</label></li>
    <li><input type="checkbox" id="part_time" checked="true"><label for="part_time">Medio tiempo</label></li>
    <li><input type="checkbox" id="flexible" checked="true"><label for="flexible">Horario flexible</label></li>
    <li><input type="checkbox" id="remote" checked="true"><label for="remote">Remoto</label></li>
  </ul>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer" class="clear span-24 last">
  <div>
    <ul>
      <li><%= link_to "publicar ofertas", new_job_path %></li>
      <li><%= link_to "acerca de", acerca_de_path %></li>
      <li><%= link_to "términos y condiciones", terminos_path %></li>
      <li><%= link_to "política de privacidad", privacidad_path %></li>
      <li><%= link_to "código abierto", codigo_path %></li>
    </ul>
      
    <ul id="follow">
      <li><%= image_tag "siguenos.png", :alt=> "Siguenos"%></li>
      <li><%= link_to (image_tag "facebook_footer.png", :alt => "FB Rubypros"), "http://www.facebook.com/OfertasHacker", :target=>:_blank %></li>
      <li><%= link_to (image_tag "twitter_footer.png", :alt => "Twitter"), "http://www.twitter.com/ofertashacker", :target =>:_blank %></li>
    </ul>
  </div>
</div>

app/views/layouts/_head.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title><%= @content_for_title %>Ofertas Hacker</title>

<!--[if lte IE 8]>
  <link rel="stylesheet" href="blueprint/ie.css" type="text/css" media="screen, projection">
<![endif]-->

<%= stylesheet_link_tag 'blueprint/screen', :media=>"screen, projection" %>
<%= stylesheet_link_tag 'blueprint/print', :media=>"print" %>

<!--[if lte IE 7]>
  <%= stylesheet_link_tag 'style_IElte7' %>
<![endif]-->

<!--[if IE 8]>
  <%= stylesheet_link_tag 'style_IE8' %>
<![endif]-->

<!--Arvo -->
<link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Arvo:bold' rel='stylesheet' type='text/css'>

<link rel="icon" type="image/x-icon" href="<%= full_image_url('favicon.ico') %>">
<%= javascript_include_tag 'application' %>
<%= stylesheet_link_tag "application" %>

<%= csrf_meta_tag %>

<script type="text/javascript" src="https://loader.engage.gsfn.us/loader.js"></script>
<script type="text/javascript">
if (typeof GSFN !== "undefined") { GSFN.loadWidget(3202,{"containerId":"getsat-widget-3202"}); }
</script>

<%= yield(:head) %>

app/views/layouts/_header.html.erb
<div id="header" class="clear full" style='position:static'>
  <div class='full'>
    <div class='container'>
      <div class="span-24 topMenu">
        <ul>
          <% if current_company %>
            <li id="ofertas" class="left"><%= link_to "<span>Ofertas</span>".html_safe, ofertas_path() %></li>
            <li id="empresas" class="left"><%= link_to "<span>Empresas</span>".html_safe, empresas_path %></li>
            <li id="salir" class="right"><%= link_to "<span>Salir</span>".html_safe, destroy_company_session_path() %></li>
            <li id="perfil" class="right"><%= link_to "<span>Mi empresa</span>".html_safe, company_path(current_company) %></li>
            <li id="publicar" class="right"><%= link_to "<span>Publicar oferta</span>".html_safe,  nueva_oferta_path() %></li>
            <%if can? :manage, RequiredSkill%>
              <li id="skills" class="left"><%= link_to "<span>Habilidades</span>".html_safe, required_skills_path %></li>
            <%end%>
          <% else %>
            <li id="entrar" class="right"><%= link_to "<span>Iniciar sesión</span>".html_safe, new_company_session_path() %></li>
            <li id="registrate" class="right"><%= link_to "<span>¿Empresa? Regístrate</span>".html_safe, new_company_registration_path()%></li>
            <li id="empresas" class="right"><%= link_to "<span>Empresas</span>".html_safe, empresas_path %></li>
            <li id="ofertas" class="right"><%= link_to "<span>Ofertas</span>".html_safe, ofertas_path() %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  
  <div class='main_header full'>
    <div class='container'>
      <div class="logo clear span-6">
        <%= link_to (image_tag "logo.png", :alt=>"Rubypros"), root_path %>
      </div>

      <%= yield :search_form %>
    </div>
  </div>

  <%= yield :search_filters %>
</div>

app/views/layouts/_search.html.erb
<%= form_tag(job_search_path, :method => :get, :class => 'search_form') do%>
  <div class='main_row'>
    <div class='row'>
      <%= label_tag 'keywords', "Busco" %>
      <%= text_field_tag 'keywords', params[:keywords], :class => 'large', :placeholder => 'Oferta, Compañia o Habilidad' %>

      <%= label_tag 'location', "en" %>
      <%= text_field_tag 'location', params[:location], :class => 'full_autocomplete medium', :placeholder => 'Ciudad o País' %>

      <%= hidden_field_tag 'location_id', params[:location_id] %>
      <%= hidden_field_tag 'location_type',  params[:location_type] %>
    </div>

    <%= submit_tag 'Buscar', :class => 'big_button' %>
  </div>
<% end %>

<%= hidden_field_tag 'old_location_id', params[:location_id] %>
<%= hidden_field_tag 'old_location_type',  params[:location_type] %>
<%= hidden_field_tag 'old_keywords',  params[:keywords] %>

app/views/layouts/_textileguide.html.erb
<table>
    <tr>
      <th>Para obtener este resultado&hellip;</th>
      <th>Escribe esto&hellip;</th>
    </tr>
    <tr>
      <td>
        <strong>Texto en negritas</strong>
      </td>
      <td>
        *Texto en negritas*
      </td>
    </tr>
    <tr>
      <td>
        <span style="font-style: italic;">Italicas</span>
      </td>
      <td>
        _Italicas_
      </td>
    </tr>
    <tr>
      <td>
        <ul>
          <li>Lista con bullets</li>
          <li>Lista con bullets</li>
        </ul>
      </td>
      <td>
          * Lista con bullets<br />
          * Lista con bullets
      </td>
    </tr>
    <tr>
      <td>
        <ol>
          <li>Numbered list</li>
          <li>Numbered list</li>
        </ol>
      </td>
      <td>
          # Lista numerada<br />
          # Lista numerada
      </td>
    </tr>
    <tr>
      <td>
        <blockquote>Bloque</blockquote>
      </td>
      <td>
          bq. Bloque
      </td>
    </tr>
    <tr>
      <td><h1>Título grande</h1></td>
      <td>h1. Título grande</td>
    </tr>
    <tr>
      <td><h2>Título normal</h2></td>
      <td>h2. Título normal</td>
    </tr>
    <tr>
      <td><a href="http://www.innku.com">Innku</a></td>
      <td>"Innku":http://www.innku.com</td>
    </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <!--[if IE 9 ]><html class="ie9" lang="en"> <![endif]-->
  <head>
    <%= render 'layouts/head'%>
  </head>

  <body>
    <div id="getsat-widget-3202"></div>
    <%= render 'layouts/header'%>

    <div class='container'>
      <% flash.each do |name, msg| %>
        <% unless msg.blank?%>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end%>
      <% end %>

      <%= content_tag :h1, yield(:title) if show_title? %>

      <div id='content' class="mainContent clear span-24">
        <%= yield %>
      </div>
    </div>

    <%= render 'layouts/footer'%>
    <%= yield :bottom %>
  </body>
</html>

app/views/layouts/double_div.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <!--[if IE 9 ]><html class="ie9" lang="en"> <![endif]-->
  <head>
    <%= render 'layouts/head'%>
  </head>

  <body class='with_filters'>
      <%= render 'layouts/header'%>

      <div class='container'>
        <% flash.each do |name, msg| %>
          <% unless msg.blank?%>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          <% end%>
        <% end %>

        <%= content_tag :h1, yield(:title) if show_title? %>

        <div id='content' class="job_search">
          <%= yield %>
        </div>
      </div>
    <%= render 'layouts/footer'%>
     <%= yield :bottom %>
  </body>
</html>